callbackform/urls.py
"""Defines URL patterns for callbackforms."""

from django.urls import path
from . import views


urlpatterns = [
    path('confirmation/', views.confirmation),
    path('callbackform/', views.print_callback_form),
    path('', views.home),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('callbackform.urls')),
    path('success/', include('callbackform.urls')),
    path('callbackform/', include('callbackform.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

callbackform/models.py
from django.db import models
from django.db.models.deletion import PROTECT
from datetime import datetime

# Create your models here.

STATUS_CHOICES = [
    ('o', 'Outstanding'),
    ('a', 'Archived'),
]

class Callback (models.Model):
    name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    company = models.CharField(max_length=70, null=True, blank=True)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    problem_description = models.CharField(max_length=1000)
    submitted_date_time = models.DateTimeField(default = datetime.now, null=True, blank=True)
    support_date_time = models.DateTimeField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='Not reviewed')

    def __str__(self):
        return self.subject

# class Archieved (models.Model):
#     callbackform = models.ForeignKey(CallbackForm, on_delete=PROTECT)

callbackform/forms.py
from django.forms import ModelForm
from .models import Callback
from django import forms



class CallbackForm(forms.ModelForm):
        required_css_class = 'required'
        name = forms.CharField(max_length= 50, required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter your name'}))
        phone_number = forms.CharField(required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
        company = forms.CharField(max_length= 70, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
        email = forms.EmailField(max_length= 50, required=True, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Enter your e-mail address'}))
        subject = forms.CharField(max_length= 200, required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter your subject title'}))
        problem_description = forms.CharField(max_length= 1000, required= True, widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Describe your issue'}))
        support_date_time = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])


        class Meta:
            model = Callback
            fields = ('name', 'phone_number', 'company', 'email', 'subject', 'problem_description', 'support_date_time')

callbackform/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Callback
from .forms import CallbackForm

# Create your views here.

def print_callback_form(request):

    if request.method == 'POST':
        form = CallbackForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/confirmation/')

    else:
        form = CallbackForm()
        context = {'form': form}
        return render(request, 'callbackform/callbackform.html', context)


def confirmation(request):
    return render(request, 'confirmation.html')

def home(request):
    return render(request, 'home.html')   

callbackform/templates/callbackform/callbackform.html
{% extends 'home.html' %}
{% load static %}
{% block content %}

<form method="POST" action="" autocomplete="off">

    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="Submit" class="btn btn-success">
</form>

{% endblock content %}

callbackform/templates/callbackform/index.html
{% extends 'main.html' %}

{% block content %}

<h1>Callbackform</h1>

<p>This is our first text paragraph demo.</p>

{% endblock content %}

templates/confirmation.html
{% extends 'home.html' %}
{% load static %}
  <body>

    {% include 'navbar.html' %}

    {% block content %}

    <br>
    <p><b>Your form has been successfully submitted!</b> <br><br>
       We will get back to you as soon as possible.<br><br>
       Thank you for your patience!
      </p>

    {% endblock content %}


  </body>

</html>

templates/home.html
<!-- start with a Boilerplate html file -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>

    <link rel="stylesheet" type='text/css', media='screen', href="{% static 'callbackform.css'%}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Import bootstrap files-->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
      crossorigin="anonymous"></script>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
  
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
      integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
      integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
      crossorigin="anonymous"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
  
    <!-- XDSoft DateTimePicker -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
        integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
        integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
  </head>

<body>

</body>
<!-- this should go after your </body> -->
<link rel="stylesheet" type="text/css" href="/jquery.datetimepicker.css"/ >
<script src="/jquery.js"></script>
<script src="/build/jquery.datetimepicker.full.min.js"></script>

</html>



    <style>
      body {
        background-color:cornsilk;
      }
    </style>
  </head>

  <body>
     
    <div class="container">

        {% include 'navbar.html' %}
        {% block content %}
 
            <p>Hello and welcome to our Webby website.</p>
            <p>Fill in the contact form if you have any problems using our product.</p>

        {% endblock content %}

    </div>


<!-- Function that edit datetime picker functionality -->
<script>
  var logic = function (currentDateTime) {
    // console.log(currentDateTime.getDay());
    const working_days = [1, 2, 3, 4, 5];
    var actualdate = new Date();
    if ((actualdate.getDate() < currentDateTime.getDate()) || (actualdate.getMonth() < currentDateTime.getMonth())) {
      if (working_days.includes(currentDateTime.getDay())) {
        console.log('working day');
        this.setOptions({
          minTime: '08:00',
          allowTimes: ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00',
            '13:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30', '17:00', '17:30', '18:00', '18:30', '19:00', '19:30', '20:00'],
        });
      } else if (currentDateTime.getDay() == 6) {
        this.setOptions({
          minTime: '08:00',
          allowTimes: ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '12:00', '12:30', '13:00'],
        });
      } else {
        this.setOptions({
          minTime: '24:00',
          allowTimes: ['00:00'],
        });
      }
    } else {
      this.setOptions({
        minTime: '24:00',
        allowTimes: ['00:00'],
      });
    }
  };
</script>
<!-- Function setup datetime picker -->
<script>
  $(function () {
    $("#id_support_date_time").datetimepicker({
      format: 'Y-m-d H:i',
      onChangeDateTime: logic,
      onShow: logic,
    });
  });
</script>
<!-- Function that adds class for bootstrap class form-control to datetime picker -->
<script>
  $function() 
  {
    $("#id_support_date_time").addClass('form-control');
  };
</script>


  </body>


</html>

templates/main.html
<!-- start with a Boilerplate html file -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to Webby!</title>
    <!-- <link rel="stylesheet" href="style.css">
    <script src="index.js"></script> -->

    <style>
      body {
        background-color:cornsilk;
      }
    </style>
  </head>

  <body>

    {% include 'navbar.html' %}

    {% block content %}

    <p>This will be our company's short story.</p>

    {% endblock content %}


  </body>

</html>

templates/navbar.html
<h1>Welcome to Webby!</h1>

<a href="/">Home</a>
<a href="/callbackform/">Contact Form</a>
<hr>